name: Build and test the Nextjs App

on:
  push:
    paths:
      - "frontend/**"
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
        env:
          NEXT_PUBLIC_FB_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FB_AUTH_DOMAIN }}
          NEXT_PUBLIC_FB_API_KEY: ${{ secrets.NEXT_PUBLIC_FB_API_KEY }}
          NEXT_PUBLIC_FB_PID: ${{ secrets.NEXT_PUBLIC_FB_PID }}
          NEXT_PUBLIC_FB_STORAGE: ${{ secrets.NEXT_PUBLIC_FB_STORAGE }}
          NEXT_PUBLIC_FB_MESSAGING: ${{ secrets.NEXT_PUBLIC_FB_MESSAGING }}
          NEXT_PUBLIC_FB_APPID: ${{ secrets.NEXT_PUBLIC_FB_APPID }}
          NEXT_PUBLIC_FB_MEASUREID: ${{ secrets.NEXT_PUBLIC_FB_MEASUREID }}
      - run: npm test
